FROM ruby:2.6-slim

RUN mkdir -p /srv/docs/build

WORKDIR /srv/docs

VOLUME /srv/docs/source

COPY . /srv/docs

RUN apt-get update \
    && apt-get install -y --no-install-recommends \
        build-essential \
        nodejs \
    && gem install bundler \
    && bundle install \
    && apt-get remove -y build-essential \
    && apt-get autoremove -y \
    && rm -rf /var/lib/apt/lists/*

CMD ["bundle", "exec", "middleman", "build"]
